apiVersion: batch/v1
kind: Job
metadata:
  name: todo-insert-new
  annotations:
    argocd.argoproj.io/hook: PostSync # <1>
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: httpie
          image: alpine/httpie:2.4.0
          imagePullPolicy: Always
          command: ["http"]
          args:
            [
              "POST",
              "todo-gitops:8080/api",
              "title=Some other todo task",
              "--ignore-stdin"
            ]
      restartPolicy: Never
  backoffLimit: 1